Renamed osx.install to install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 set -e
-base=$HOME/.p9p
+base=$HOME/.p9p2
 
 install_darwin()
 {
@@ -16,25 +16,30 @@ install_darwin()
 	done
 }
 
+if [ ! -d $base ]; then
+	echo "$base not found or doesn't exist, please set \$base in $0 to the correct path"
+	exit 2
+fi
+
 if [ $(uname -s) = Darwin ]; then
 	install_darwin
 fi
 
 # Get devdrawserver and gitfiles
 [ -d $base/cmd/tab ] && {
-	cd $base/cmd/tab && mk install
+	cd $base/cmd/tab && mk install && mk clean
 }
 
 [ ! -d $base/cmd/devdrawserver ] && {
 	cd $base/cmd/
 	git clone ssh://git@github.com/mariusae/devdrawserver.git
-	cd $base/cmd/devdrawser && mk install
+	cd $base/cmd/devdrawser && mk install && mk clean
 }
 
 [ ! -d $base/cmd/gitfiles ] && {
 	cd $base/cmd/
 	git clone ssh://git@github.com/mariusae/gitfiles.git
-	cd $base/cmd/gitfiles && mk install
+	cd $base/cmd/gitfiles && mk install && mk clean
 }
 
 cd $base
